server:
  port: 8080

spring:
  profiles:
    active: local # 로컬 프로파일 활성화

  output:
    ansi:
      enabled: always # ANSI 콘솔 색상 활성화 (JUnit 테스트 포함)

  jpa:
    hibernate:
      ddl-auto: update # 테이블 생성 및 업데이트 전략 (create, create-drop, update, validate, none)
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        highlight_sql: true # SQL 하이라이트 출력
        use_sql_comments: true # JPQL SQL 주석 사용
        default_batch_fetch_size: 100 # 기본 배치 크기 설정

app:
  props:
    jwt:
      secret-key: 1234567890123456789012345678901234567890
      access-token-expiration-period: 15   # 15분
      refresh-token-expiration-period: 1440  # 24시간 60 * 24 = 1440분

---

spring:
  config:
    activate:
      on-profile: test

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 경로 설정

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/friendzoo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: friendzoo
    password: friendzoo

logging:
  level:
    org.hibernate.SQL: debug # Hibernate SQL 로그 레벨
    org.hibernate.orm.jdbc.bind: trace # Hibernate SQL 바인딩 로그 레벨
    org.springframework.transaction.interceptor: trace # Spring 트랜잭션 인터셉터 로그 레벨

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    hikari:
      max-lifetime: 600000  # 최대 수명 (밀리초)
      idle-timeout: 300000 # 유휴 시간 (밀리초)
      connection-timeout: 30000 # 연결 시간 초과 (밀리초)

app:
  aws:
    ec2:
      instance-front-url: http://43.203.42.37

logging:
  level:
    org.hibernate.SQL: error # Hibernate SQL 로그 레벨
